### ISSUE TITLE
Can't install audio module

### ISSUE THREAD

**Issue by Hamsterland** [stephen-huan/anime-music-quiz#4]
A basically know zero Python and there is a problem installing the "audio" module. 
```
Collecting audio
  Using cached audio-1.5.0.tar.gz (2.1 kB)
Collecting audio.bitstream
  Using cached audio.bitstream-2.5.4.tar.gz (1.2 kB)
Collecting bitstream==2.5.4
  Using cached bitstream-2.5.4.tar.gz (168 kB)
Collecting audio.coders
  Using cached audio.coders-4.0.2.tar.gz (682 kB)

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mdabr\.virtualenvs\anime-music-quiz-xnUNYISd\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mdabr\\AppData\\Local\\Temp\\pip-install-5dhrmu9a\\audio-coders_33068b5a02004254924d3ec057050f70\\setup.py'"'"'; __file__='"'"'C:\\Users\\mdabr\\AppData\\Local\\Temp\\pip-install-5dhrmu9a\\audio-coders_33068b5a02004254924d3ec057050f70\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mdabr\AppData\Local\Temp\pip-pip-egg-info-5lct4ru8'
         cwd: C:\Users\mdabr\AppData\Local\Temp\pip-install-5dhrmu9a\audio-coders_33068b5a02004254924d3ec057050f70\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mdabr\AppData\Local\Temp\pip-install-5dhrmu9a\audio-coders_33068b5a02004254924d3ec057050f70\setup.py", line 5, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Hamsterland** [comment]
Looks like some stupid issue with renaming ConfigParser to configparser. Any idea how to solve?

**Comment by stephen-huan** [comment]
The `audio` module isn't necessary. The required packages can be found in the [Pipfile](https://github.com/stephen-huan/anime-music-quiz/blob/master/Pipfile) and installed with `pipenv install` (get `pipenv` from https://pipenv.pypa.io/en/latest/).

Pipenv isn't strictly necessary either; here's `pip freeze` for reference:
```
audio2numpy==0.1.2
cffi==1.14.4
click==7.1.1
covidify==1.0.1
cycler==0.10.0
docopt==0.6.2
ffmpeg==1.4
gitdb==4.0.2
GitPython==3.1.0
kiwisolver==1.1.0
matplotlib==3.2.1
numpy==1.19.5
pandas==1.0.3
Pillow==7.0.0
pyarrow==0.16.0
pycparser==2.20
pydub==0.24.1
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
scipy==1.6.0
selenium==3.141.0
six==1.14.0
smmap==3.0.1
sounddevice==0.4.1
tqdm==4.43.0
urllib3==1.26.2
XlsxWriter==1.2.8
```
Note that it doesn't include the `audio` module.
Save the above text as `requirements.txt` and install with `pip install -r requirments.txt`.
